use bitflags::bitflags;
use vma_sys::*;

bitflags! {
    #[repr(transparent)]
    pub struct AllocationCreateFlags: u32 {
        const DEDICATED_MEMORY = VMA_ALLOCATION_CREATE_DEDICATED_MEMORY_BIT;
        const NEVER_ALLOCATE = VMA_ALLOCATION_CREATE_NEVER_ALLOCATE_BIT;
        const MAPPED = VMA_ALLOCATION_CREATE_MAPPED_BIT;
        const USER_DATA_COPY_STRING = VMA_ALLOCATION_CREATE_USER_DATA_COPY_STRING_BIT;
        const UPPER_ADDRESS = VMA_ALLOCATION_CREATE_UPPER_ADDRESS_BIT;
        const DONT_BIND = VMA_ALLOCATION_CREATE_DONT_BIND_BIT;
        const WITHIN_BUDGET = VMA_ALLOCATION_CREATE_WITHIN_BUDGET_BIT;
        const CAN_ALIAS = VMA_ALLOCATION_CREATE_CAN_ALIAS_BIT;
        const HOST_ACCESS_SEQUENTIAL_WRITE = VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT;
        const HOST_ACCESS_RANDOM = VMA_ALLOCATION_CREATE_HOST_ACCESS_RANDOM_BIT;
        const HOST_ACCESS_ALLOW_TRANSFER_INSTEAD = VMA_ALLOCATION_CREATE_HOST_ACCESS_ALLOW_TRANSFER_INSTEAD_BIT;
        const STRATEGY_MIN_MEMORY = VMA_ALLOCATION_CREATE_STRATEGY_MIN_MEMORY_BIT;
        const STRATEGY_MIN_TIME = VMA_ALLOCATION_CREATE_STRATEGY_MIN_TIME_BIT;
        const STRATEGY_MIN_OFFSET = VMA_ALLOCATION_CREATE_STRATEGY_MIN_OFFSET_BIT;
        const STRATEGY_BEST_FIT = VMA_ALLOCATION_CREATE_STRATEGY_BEST_FIT_BIT;
        const STRATEGY_FIRST_FIT = VMA_ALLOCATION_CREATE_STRATEGY_FIRST_FIT_BIT;
        const STRATEGY_MASK = VMA_ALLOCATION_CREATE_STRATEGY_MASK;
    }
}

bitflags! {
    #[repr(transparent)]
    pub struct AllocatorCreateFlags: u32 {
        const EXTERNALLY_SYNCHRONIZED = VMA_ALLOCATOR_CREATE_EXTERNALLY_SYNCHRONIZED_BIT;
        const KHR_DEDICATED_ALLOCATION = VMA_ALLOCATOR_CREATE_KHR_DEDICATED_ALLOCATION_BIT;
        const KHR_BIND_MEMORY2 = VMA_ALLOCATOR_CREATE_KHR_BIND_MEMORY2_BIT;
        const EXT_MEMORY_BUDGET = VMA_ALLOCATOR_CREATE_EXT_MEMORY_BUDGET_BIT;
        const AMD_DEVICE_COHERENT_MEMORY = VMA_ALLOCATOR_CREATE_AMD_DEVICE_COHERENT_MEMORY_BIT;
        const BUFFER_DEVICE_ADDRESS = VMA_ALLOCATOR_CREATE_BUFFER_DEVICE_ADDRESS_BIT;
        const EXT_MEMORY_PRIORITY = VMA_ALLOCATOR_CREATE_EXT_MEMORY_PRIORITY_BIT;
    }
}

bitflags! {
    #[repr(transparent)]
    pub struct DefragmentationFlags: u32 {
        const ALGORITHM_FAST = VMA_DEFRAGMENTATION_FLAG_ALGORITHM_FAST_BIT;
        const ALGORITHM_BALANCED = VMA_DEFRAGMENTATION_FLAG_ALGORITHM_BALANCED_BIT;
        const ALGORITHM_FULL = VMA_DEFRAGMENTATION_FLAG_ALGORITHM_FULL_BIT;
        const ALGORITHM_EXTENSIVE = VMA_DEFRAGMENTATION_FLAG_ALGORITHM_EXTENSIVE_BIT;
        const ALGORITHM_MASK = VMA_DEFRAGMENTATION_FLAG_ALGORITHM_MASK;
    }
}

bitflags! {
    #[repr(transparent)]
    pub struct PoolCreateFlags: u32 {
        const IGNORE_BUFFER_IMAGE_GRANULARITY = VMA_POOL_CREATE_IGNORE_BUFFER_IMAGE_GRANULARITY_BIT;
        const LINEAR_ALGORITHM = VMA_POOL_CREATE_LINEAR_ALGORITHM_BIT;
        const ALGORITHM_MASK = VMA_POOL_CREATE_ALGORITHM_MASK;
    }
}

bitflags! {
    #[repr(transparent)]
    pub struct VirtualAllocationCreateFlags: u32 {
        const UPPER_ADDRESS = VMA_VIRTUAL_ALLOCATION_CREATE_UPPER_ADDRESS_BIT;
        const STRATEGY_MIN_MEMORY = VMA_VIRTUAL_ALLOCATION_CREATE_STRATEGY_MIN_MEMORY_BIT;
        const STRATEGY_MIN_TIME = VMA_VIRTUAL_ALLOCATION_CREATE_STRATEGY_MIN_TIME_BIT;
        const STRATEGY_MIN_OFFSET = VMA_VIRTUAL_ALLOCATION_CREATE_STRATEGY_MIN_OFFSET_BIT;
        const STRATEGY_MASK = VMA_VIRTUAL_ALLOCATION_CREATE_STRATEGY_MASK;
    }
}

bitflags! {
    #[repr(transparent)]
    pub struct VirtualBlockCreateFlags: u32 {
        const LINEAR_ALGORITHM = VMA_VIRTUAL_BLOCK_CREATE_LINEAR_ALGORITHM_BIT;
        const ALGORITHM_MASK = VMA_VIRTUAL_BLOCK_CREATE_ALGORITHM_MASK;
    }
}

#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct DefragmentationMoveOperation(u32);
impl DefragmentationMoveOperation {
    pub const COPY: Self = Self(VMA_DEFRAGMENTATION_MOVE_OPERATION_COPY);
    pub const IGNORE: Self = Self(VMA_DEFRAGMENTATION_MOVE_OPERATION_IGNORE);
    pub const DESTROY: Self = Self(VMA_DEFRAGMENTATION_MOVE_OPERATION_DESTROY);
}

#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct MemoryUsage(u32);
impl MemoryUsage {
    pub const UNKNOWN: Self = Self(VMA_MEMORY_USAGE_UNKNOWN);
    pub const GPU_ONLY: Self = Self(VMA_MEMORY_USAGE_GPU_ONLY);
    pub const CPU_ONLY: Self = Self(VMA_MEMORY_USAGE_CPU_ONLY);
    pub const CPU_TO_GPU: Self = Self(VMA_MEMORY_USAGE_CPU_TO_GPU);
    pub const GPU_TO_CPU: Self = Self(VMA_MEMORY_USAGE_GPU_TO_CPU);
    pub const CPU_COPY: Self = Self(VMA_MEMORY_USAGE_CPU_COPY);
    pub const GPU_LAZILY_ALLOCATED: Self = Self(VMA_MEMORY_USAGE_GPU_LAZILY_ALLOCATED);
    pub const AUTO: Self = Self(VMA_MEMORY_USAGE_AUTO);
    pub const AUTO_PREFER_DEVICE: Self = Self(VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE);
    pub const AUTO_PREFER_HOST: Self = Self(VMA_MEMORY_USAGE_AUTO_PREFER_HOST);
}
